### ISSUE TITLE
Disambiguate link on `reset` page

### ISSUE THREAD

**Issue by alroman** [ucla/logon#1]
There is a link to a `UCLA Logon Service Request Form`

```
javascript:warn_pii("/forms/service_request.pdf");
```

Not sure where this is coming from.

**Comment by erutan** [comment]
It's https://logon-asm1.logon.ucla.edu/forms/service_request.pdf - I just pulled a lot of the content from logon.ucla.edu in terms of official wording (though I've pared a few things down). Not exactly sure why it has a warning pop-up, doesn't seem very useful. https://logon-asm1.logon.ucla.edu/passreset.php

**Comment by alroman** [comment]
Got it.  Will ask him.
