### ISSUE TITLE
make the duo iframe taller

### ISSUE THREAD

**Issue by erutan** [ucla/logon#10]
The bottom gets cut off sometimes on pages with more options.

**Comment by iamucla** [comment]
@gregfutami this is a small change in the DUO twig template.

**Comment by erutan** [comment]
https://css-tricks.com/snippets/jquery/fit-iframe-to-content/

**Comment by erutan** [comment]
http://davidjbradshaw.github.io/iframe-resizer/

bah, needs a js file placed in what gets loaded in the `<iframe>`, nevermind
