### ISSUE TITLE
Typo in mfa page

### ISSUE THREAD

**Issue by iamucla** [ucla/logon#11]
`Authentiation` =>  `Authentication`

**Comment by albertwu** [comment]
what page is this on?

**Comment by erutan** [comment]
single page mfa. to be fair the commit description turned out to be pretty accurate. ;)

https://github.com/ucla/logon/commit/c0deb28dd0e091f43305f17958aa98dec6171d34

**Comment by albertwu** [comment]
fixed. now returning to your regular programming.
