### ISSUE TITLE
Broken Date of Birth form rendering on FF

### ISSUE THREAD

**Issue by alroman** [ucla/logon#2]
Seems to be FF only

<img width="812" alt="screen shot 2016-02-03 at 5 08 32 pm" src="https://cloud.githubusercontent.com/assets/686549/12802579/c9d2af96-ca98-11e5-8512-cf45eca303ba.png">

**Comment by erutan** [comment]
It's everything except blink iirc, this is the webshim stuff we talked about before. Now that I'm using Zurb's Abide for form validation I don't know if I really need it anymore, I might just do a one-off polyfill for the date field.

**Comment by erutan** [comment]
Dropping webshim for polyfills (this was the only thing left I was using, and it is buggy). I'll toss something up later, but for now it degrades gracefully (just no widget in non-chrome).

Most likely https://github.com/chemerisuk/better-dateinput-polyfill

**Comment by erutan** [comment]
not really critical, will be addressed in the front-end todo issue
