### ISSUE TITLE
Better logo for DUO SDK

### ISSUE THREAD

**Issue by alroman** [ucla/logon#5]
The current logo is tiny and blurry and does not have a transparent background.

<img width="746" alt="screen shot 2016-02-23 at 10 45 18 am" src="https://cloud.githubusercontent.com/assets/686549/13262602/91a82fb0-da1a-11e5-8b99-ffcfc188adbf.png">

**Comment by alroman** [comment]
This logo seems to also be used for DUO push notifications.

**Comment by erutan** [comment]
https://github.com/ucla/logon/blob/master/src/assets/img/ucla-blue.png try using this. Blurry is just due to resizing, unless it's always going to be one length it'll be a bit odd, but it's better to downsample rather than upsample.

**Comment by alroman** [comment]
Yeah, didn't occur to me to look in our current assets.  I had been looking for a better image in the UCLA branding site, but they don't have high res PNG on demand.  This image also renders on DUO push.
