### ISSUE TITLE
Go flatter... but not too flat

### ISSUE THREAD

**Issue by iamucla** [ucla/logon#9]
I wanted to push the site to a 'flatter' look -- that is removing rounded corners and padded edges so that all boxes always push against the edge of the content box.  

@albertwu @erutan Thoughts?

<img width="988" alt="screen shot 2016-03-21 at 5 58 13 pm" src="https://cloud.githubusercontent.com/assets/17581353/13939059/8394a87a-ef8e-11e5-89b6-7a58061fa223.png">

**Comment by erutan** [comment]
Something we can think of for an internal app (next iteration of heim/gjaller), but it's a bit of a departure from any UCLA norms (and logon is a pretty simple application to really benefit from tiles).
